name: Build & Release bees

on:
  push:
    tags:
      - '*'    # build & release on any tag push, e.g. v1.2.3

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ${{ matrix.runs_on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-linux-glibc
            runs_on: ubuntu-24.04
          - target: aarch64-linux-glibc
            runs_on: ubuntu-24.04-arm

    env:
      JOBS: 8

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential autoconf automake libtool pkg-config \
            libxxhash-dev libzstd-dev zlib1g-dev liblz4-dev libacl1-dev \
            libbtrfs-dev markdown upx-ucl

      - name: Configure & build bees
        run: |
          set -euxo pipefail
          # build; statically link libstdc++/libgcc for fewer runtime deps
          make -j"${JOBS}" CFLAGS="-O2 -pipe" CXXFLAGS="-O2 -pipe" LDFLAGS="-static-libstdc++ -static-libgcc"
          strip -s bin/bees || true
          bin/bees --version || true
          upx bin/bees || true

      - name: Package tarball
        run: |
          set -euxo pipefail
          VERSION="${GITHUB_REF_NAME}"
          OUT="bees-${VERSION}-${{ matrix.target }}"
          mkdir -p "staging/${OUT}/bin"
          install -Dm755 bin/bees "staging/${OUT}/bin/bees"
          install -Dm644 COPYING "staging/${OUT}/COPYING"
          install -Dm644 README.md "staging/${OUT}/README.md"
          tar -C staging -cJf "${OUT}.tar.xz" "${OUT}"
          sha256sum "${OUT}.tar.xz" > "${OUT}.tar.xz.SHA256"

      - name: Upload artifact (per-arch)
        uses: actions/upload-artifact@v4
        with:
          name: bees-${{ matrix.target }}
          overwrite: true
          if-no-files-found: error
          path: |
            bees-${{ github.ref_name }}-${{ matrix.target }}.tar.xz
            bees-${{ github.ref_name }}-${{ matrix.target }}.tar.xz.SHA256

  release:
    name: release ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List artifacts
        run: ls -lR dist

      - name: Create / Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/**/bees-*.tar.xz
            dist/**/bees-*.tar.xz.SHA256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
